fix: fixing sonarcloud test

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -28,9 +28,21 @@ jobs:
 
       - name: Run tests with coverage
         run: npm run test:ci
+        env:
+          CI: true
+
+      - name: Check test report generation
+        run: |
+          if [ -f coverage/test-report.xml ]; then
+            echo "Test report generated successfully"
+          else
+            echo "Test report not found!"
+            exit 1
+          fi
 
       - name: SonarCloud Scan
-        uses: SonarSource/sonarcloud-github-action@master
+        uses: SonarSource/sonarqube-scan-action@v5.0.0
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: https://sonarcloud.io
